### PR TITLE
position statement - Hardened JavaScript

### PR DESCRIPTION
**Pull request by naugtur**

### CODE REVIEW

**Comment by dontcallmedom** [comment]
@naugtur many thanks for your submission! Unfortunately, due to a low level of submissions within the requested timeline, the Program Committee doesn't feel like it can justify holding a 2 days workshops in the original timeframe of June 7-8. The Program Committee will get back to you both on the content of the submission and a possibly new format/schedule in a couple of weeks.

**Comment by tidoust** [comment]
Hi @naugtur,

Thanks again for your submission! The Secure the Web Forward workshop was re-launched as a virtual event on 26-28 September 2023 and the program committee has reviewed position papers that were submitted following the initial call for participation. We are pleased to inform your position statement has been accepted and that we will publish and reference it on the workshop's web site, and use it as input to build the agenda of the workshop.

The workshop will primarily be virtual across three two-hour virtual sessions on the 26th, 27th and 28th of September. We hope that these new dates, pending details on actual times, work for you!

Please note that the virtual sessions are targeted at actively discussing topics. We may briefly ask people to introduce concepts or perspectives but do not plan to have formal presentations of the position papers. Program and logistics should be announced beginning of August.

**Comment by naugtur** [comment]
I'm helping with a community conference on 29th and probably will be involved on 28th as well. I'd appreciate if this topic was early in the agenda. Preferably on day one.
Looking forward to the meetings.

**Comment by tidoust** [comment]
Noted, thanks!

**Comment by tidoust** [comment]
Hi @naugtur. Your topic is [currently scheduled](https://www.w3.org/2023/03/secure-the-web-forward/agenda.html) during the first session, on 26th. By any chance, would you be amenable to moving it to the second session, on 27th? Or will that clash with the community conference you mentioned? (Both calls will be at 3pm UTC for 2 hours)

**Comment by naugtur** [comment]
@tidoust 
Yes. Let's move it.

The one limitation is my talk is interconnected with Gal's and itd make sense for the order to remain unchanged, even on the same day.

**Comment by tidoust** [comment]
Great, thanks! I'll put your talk first in second session then.

**Comment by naugtur** [comment]
@tidoust please unmerge the sessions tho. We'd need separate discussion blocks.
We'd like to keep the originally allotted times for both topics independently.

**Comment by tidoust** [comment]
Ah, that's on purpose, @naugtur. Second session is split into two only because Artur cannot join the first hour, but we would have merged all presentations otherwise, as done for the first and third session.

Goal is to have 10mn presentation + 5mn Q&A for each paper. Then, once papers have been presented, an open discussion on the topic at large, which will no doubt touch on different, and potentially disjoint, aspects of the papers having been presented.

**Comment by naugtur** [comment]
That's new. But hey, youre running the show and I'll defer to your judgement

**Pull request merged**
